apiVersion: v1
kind: Service
metadata:
  labels:
    app: span
  name: span
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: span
    tier: backend
  sessionAffinity: None
  type: LoadBalancer